language: node_js

node_js:
  - "0.12"

# whitelist
branches:
  only:
    - master
    - stable

addons:
  code_climate:
    repo_token: 0597e5fa0705b17a4c02053447c4f6a5cb06009492f606f9033208505c2939d6

before_script:
  - npm install -g codeclimate-test-reporter

script: npm test

after_script:
  - codeclimate < ./build/coverage/lcov.info
  - cat './build/coverage/report-lcovonly.info' | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    - vinicius.linck@grupoapi.net.br
  hipchat:
    - VaQguLvxrFuAjOHi2KRfLBYXchJz6ToYT74R2RKs@aruba.js
  notify: true
